default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: rails_5_api_development

test:
  <<: *default
  database: rails_5_api_test

production:
  <<: *default
  database: rails_5_api_production
  username: rails_5_api
  password: <%= ENV['RAILS_5_API_DATABASE_PASSWORD'] %>
